# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"print_something": "00_core.ipynb",
         "make_changes_in_colab": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://ryanfras.github.io/vizdato/"

git_url = "https://github.com/ryanfras/vizdato/tree/master/"

def custom_doc_links(name): return None
