# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['print_something', 'make_changes_in_colab']

# Cell
def print_something():
    print('This is for fun')

# Cell
def make_changes_in_colab():
  print('This was done in colab')